### ISSUE TITLE
cannot load such file -- bundler/setup (LoadError)

### ISSUE THREAD

**Issue by chabgood** [gbarillot/rails-vue-demo-app#1]
per the instructions I get this when doing foreman start:

`
foreman start
Ignoring bcrypt-3.1.11 because its extensions are not built. Try: gem pristine bcrypt --version 3.1.11
Ignoring bindex-0.5.0 because its extensions are not built. Try: gem pristine bindex --version 0.5.0
Ignoring byebug-10.0.0 because its extensions are not built. Try: gem pristine byebug --version 10.0.0
Ignoring ffi-1.9.23 because its extensions are not built. Try: gem pristine ffi --version 1.9.23
Ignoring nio4r-2.2.0 because its extensions are not built. Try: gem pristine nio4r --version 2.2.0
Ignoring nokogiri-1.8.2 because its extensions are not built. Try: gem pristine nokogiri --version 1.8.2
Ignoring puma-3.11.3 because its extensions are not built. Try: gem pristine puma --version 3.11.3
Ignoring sqlite3-1.3.13 because its extensions are not built. Try: gem pristine sqlite3 --version 1.3.13
Ignoring websocket-driver-0.6.5 because its extensions are not built. Try: gem pristine websocket-driver --version 0.6.5
13:27:22 web.1     | started with pid 2054
13:27:22 webpack.1 | started with pid 2055
13:27:22 webpack.1 | Ignoring bcrypt-3.1.11 because its extensions are not built. Try: gem pristine bcrypt --version 3.1.11
13:27:22 webpack.1 | Ignoring bindex-0.5.0 because its extensions are not built. Try: gem pristine bindex --version 0.5.0
13:27:22 webpack.1 | Ignoring byebug-10.0.0 because its extensions are not built. Try: gem pristine byebug --version 10.0.0
13:27:22 webpack.1 | Ignoring ffi-1.9.23 because its extensions are not built. Try: gem pristine ffi --version 1.9.23
13:27:22 webpack.1 | Ignoring nio4r-2.2.0 because its extensions are not built. Try: gem pristine nio4r --version 2.2.0
13:27:22 webpack.1 | Ignoring nokogiri-1.8.2 because its extensions are not built. Try: gem pristine nokogiri --version 1.8.2
13:27:22 webpack.1 | Ignoring puma-3.11.3 because its extensions are not built. Try: gem pristine puma --version 3.11.3
13:27:22 webpack.1 | Ignoring sqlite3-1.3.13 because its extensions are not built. Try: gem pristine sqlite3 --version 1.3.13
13:27:22 webpack.1 | Ignoring websocket-driver-0.6.5 because its extensions are not built. Try: gem pristine websocket-driver --version 0.6.5
13:27:22 webpack.1 | /Users/chabgood/.rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require': cannot load such file -- bundler/setup (LoadError)
13:27:22 webpack.1 | 	from /Users/chabgood/.rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
13:27:22 webpack.1 | 	from ./bin/webpack-dev-server:15:in `<main>'
13:27:22 webpack.1 | exited with code 1
13:27:22 system    | sending SIGTERM to all processes
13:27:22 web.1     | terminated by SIGTERM
`

**Comment by gbarillot** [comment]
Hi,

Sorry for the delay. At first sight, could be a problem of gemsets, are you using RVM? Are you sure you "bundle installed" in the same gemset (or at least using the same Ruby version) as the one used to start Foreman?

**Comment by chabgood** [comment]
yes I am using rvm with gemsets.  I did get it up and running. One thing I had to do was add  - .vue to the webpacker.yml extensions. Also I had to add "webpack-cli" to the package.json

**Comment by gbarillot** [comment]
Interesting. Could you please tell me which version of Rails you're using?

**Comment by chabgood** [comment]
5.1.5

**Comment by chabgood** [comment]
ruby 2.5.0

**Comment by chabgood** [comment]
Plus I added a changed the default route as when it started up it as a blank screen.  root 'musicians#index'

**Comment by gbarillot** [comment]
FYI, mine was 5.1.4, Ruby 2.4. I'm little bit surprised by the route issue. Could be interesting if you could push a PR so I could look at all you fixes, check if it also work with 5.1.4/Ruby 2.4 and merge it if needed. At least, I could update the Readme for other users.

Thanks for the feedback!
