### ISSUE TITLE
Destroy method returning error

### ISSUE THREAD

**Issue by kwiksource** [gbarillot/rails-vue-demo-app#10]
Thank you so much for this great example.

I noticed that destroying a musician causes this error:
500, there was an error on the server side :-(

**Comment by gbarillot** [comment]
Good catch! Fixed with https://github.com/gbarillot/rails-vue-demo-app/pull/11/files
The core of the problem was the controller returning 204, which was misinterpreted as an error code. 

Sorry all for the stupid mistake :-/
