### ISSUE TITLE
puma issue in production

### ISSUE THREAD

**Issue by kozlovv529** [gbarillot/rails-vue-demo-app#12]
I tried followings.
- bundle i
- yarn i
- rake assets:precompile
- export RAILS_ENV=production
- rake db:create
- rake db:migrate
- rake db:seed
- rails s

This gets this error
`HTTP parse error, malformed request (): #<Puma::HttpParserError: Invalid HTTP format, parsing fails.>`
Could you solve it?

**Comment by gbarillot** [comment]
Did you have a look at to [this issue](https://github.com/puma/puma/issues/1128) or [this other one](https://github.com/puma/puma/issues/986)? Looks like related to SSL. 

Does it work in development mode?

**Comment by kozlovv529** [comment]
Hi, @gbarillot 
Yes, and it works well in development mode.
I have already `changed config.force_ssl = true` and removed all cookies and other datas.
But it's still.
And on Incognito browser, it is still.

**Comment by gbarillot** [comment]
Closed (inactive)

**Comment by Vuyisanani** [comment]
Hi @gbarillot , @kozlovv529 

I also just encountered the same issue in production

Have someone managed to resolve the issue?
HTTP parse error, malformed request (): #<Puma::HttpParserError: Invalid HTTP format, parsing fails.>

Thank you in advance

**Comment by gbarillot** [comment]
Honestly, it really looks like an error from Puma. Please have a look at [this thread ](https://github.com/puma/puma/issues/986). 
If I were you I'd try to fetch the most simple HTML page possible (rendering only the front layout, for instance) without any import statement (no CSS, no JS, nothing in `<head></head>`). If you still get the error:
- double check you have `config.force_ssl` to `true` in production env.
- clear you browser HSTS cache

If the error is back only when you start adding Vue in the stack, feel free to tell us more, I'll try to setup an SSL env. in production mode on my machine. Please also tell us more about your prod. env (AWS black magic / bare metal?) and full stack ( Windows/Linux? Puma version...). Some logs could also be helpful.

**Comment by Vuyisanani** [comment]
Hi @gbarillot 

Thank you for your prompt response.

Have already tried these:

- double check you have config.force_ssl to true in production env.

- clear you browser HSTS cache

Will follow up the link you sent.

Thanks
