### ISSUE TITLE
Server-Side Rendering

### ISSUE THREAD

**Issue by ghost** [gbarillot/rails-vue-demo-app#25]
Is there any way to set up a pre-rendering with this amazing SPA setup? SEO would be a great addition

**Comment by Deepidoo** [comment]
That would be awesome, if you have any idea about how to achieve this, feel free to submit a PR. Honestly, I work in the "B2B / private admin based" web apps world and have no idea about how SSR actually works.

**Comment by gbarillot** [comment]
Close for inactivity
