### ISSUE TITLE
Should HMR work just right out of the box?

### ISSUE THREAD

**Issue by gbisheimer** [gbarillot/rails-vue-demo-app#69]
I can't get HMR to work on the app. I must reload the page to see changes in JS files. I saw this on the vite ruby [site](https://vite-ruby.netlify.app/guide/rails.html#enabling-hot-module-reload-%F0%9F%94%A5):

![image](https://user-images.githubusercontent.com/3077123/167971672-f45af944-9999-478b-9faa-e64ac90e5ef8.png)

But still doesn't work. Can you give me a hand, please?

Thanks

**Comment by gbarillot** [comment]
Right, I voluntarily disabled HMR (personnal taste), but I will have a look at it today to enable it by default as well as document how to turn it off. 
I guess (?) most devs enjoy HMR and I'm an exception (?).

**Comment by gbarillot** [comment]
Ok done, HMR now default to enabled. Readme is updated. Feel free to reopen if needed...
