### ISSUE TITLE
(wrong number of arguments (given 4, expected 3) on search for users and musicians

### ISSUE THREAD

**Issue by rhelsing** [gbarillot/rails-vue-demo-app#8]
ArgumentError (wrong number of arguments (given 4, expected 3)):
09:20:03 web.1     |
09:20:03 web.1     | app/controllers/api/admin/users_controller.rb:5:in `index'

I did switch to use postgres.

**Comment by gbarillot** [comment]
Ho my... ok, I see what happens. Basically, the query string is no longer translated properly into a valid URL. 

Working on it, sorry for the convenience, pushing a fix within the next few hours.

**Comment by gbarillot** [comment]
Ok, got it. It's a ransack issue, see here: [https://github.com/activerecord-hackery/ransack/issues/948](https://github.com/activerecord-hackery/ransack/issues/947) and [https://github.com/activerecord-hackery/ransack/issues/947](https://github.com/activerecord-hackery/ransack/issues/947).

`bundle update ransack` 

fixed the issue. For the record, I just upgraded Ransack version in the current repo so no one should be annoyed with this one from now on.

Let me know if you still have issues...
